// Code generated by goctl. DO NOT EDIT.
package types

type Response struct {
	Code    int         `json:"code"`
	Message string      `json:"message,optional"`
	Data    interface{} `json:"data,optional"`
}

type FreshRequest struct {
	Path string `path:"path"`
	Key  string `path:"key"`
	Data string `json:"data,optional"`
}

type TranslateQuery struct {
	Query []string `json:"query"`
}
