

PUT http://127.0.0.1:8888/fresh/testpath/testkey HTTP/1.1
content-type: application/json

{
    "data": "[1,2,3,41]"
}

################

GET http://127.0.0.1:8888/fresh/testpath/testkey HTTP/1.1


################

POST  http://127.0.0.1:8888/translate/zh HTTP/1.1
content-type: application/json

{
    "query": ["china","book","good"]
}
